# Generated by Django 4.2.3 on 2023-08-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_name',
        ),
    ]
