# Generated by Django 4.2.3 on 2023-09-12 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0004_remove_customuser_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Description"),
                ),
                ("date", models.DateTimeField(verbose_name="Date")),
                ("file", models.URLField(verbose_name="File")),
                ("user", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
