# Generated by Django 4.2.3 on 2023-10-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0009_alter_homework_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="celery_check",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Telegram notifications"
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
