# Generated by Django 4.2.3 on 2023-10-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0010_homework_celery_check_homework_celery_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="celery_check",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Telegram notifications"
            ),
            preserve_default=False,
        ),
    ]
